# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20161231_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='shortenurl',
            name='url',
            field=models.CharField(max_length=220),
        ),
    ]
