# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20161231_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
